[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]
deployOutputs = ["dist", "src/auth", "prisma", "prisma.config.ts", "entrypoint.sh", "package*.json"]

[start]
cmd = "sh entrypoint.sh"
